### ISSUE TITLE
Accessing Frames doesn't work

### ISSUE THREAD

**Issue by rankinmark** [njasm/marionette_client#18]
I can't access and execute javascript code in frames 
`package main

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"time"

	"github.com/njasm/marionette_client"
)

func main() {
	client := marionette_client.NewClient()
	client.Connect("", 0)
	client.NewSession("", nil)

	client.Navigate("http://docs.oracle.com/javase/8/docs/api/index.html")
	client.SetContext(marionette_client.Context(marionette_client.CONTENT))
	waittime := time.Duration(4) * time.Second
	time.Sleep(waittime)
	HTMLSource(client)
		
}

func gethtml(client *marionette_client.Client) string {
	script := "return document.documentElement.outerHTML;"

	args := make([]interface{}, 0, 0) // arguments to be passed to the function

	var timeout uint
	timeout = 1000   // milliseconds
	sandbox := false // new Sandbox

	r, err := client.ExecuteScript(script, args, timeout, sandbox)
	if err == nil {
		return getJsonValue(r.Value)
	} else {
		return ""
	}

}

func getJsonValue(str string) string {
	var d map[string]string
	err := json.Unmarshal([]byte(str), &d)
	if err != nil {
		log.Println(err)
	}
	return d["value"]
}

func getscreenshot(client *marionette_client.Client) {
	client.MaximizeWindow()

	imgjson, err := client.Screenshot()
	if err == nil {
		base64txt := getJsonValue(imgjson)
		data, err := base64.StdEncoding.DecodeString(base64txt)
		if err == nil {
			err = ioutil.WriteFile("screenshot.png", data, 0644)
			if err != nil {
				log.Println(err)
			}

		}

	}

}

func HTMLSource(client *marionette_client.Client) {
	//retval := ""
	err := client.SwitchToParentFrame()
	if err == nil {
		fmt.Println(gethtml(client))
		frames, err := client.FindElements(marionette_client.By(marionette_client.TAG_NAME), "frame")
		if err == nil {
			fmt.Println("FRAMES")
			framenames := make([]string, 0, 3)
			for _, frame := range frames {
				framenames = append(framenames, frame.Attribute("name"))
			}

			for i, framename := range framenames {
				fmt.Printf("FRAME %d %s\r\n", i, framename)

				err = client.SwitchToFrame(marionette_client.By(marionette_client.NAME), framename)
				//err = client.SwitchToFrame(marionette_client.By(marionette_client.ID), frame.Id())
				if err == nil {
					fmt.Println("NOERROR")
					fmt.Println(gethtml(client))
				} else {
					fmt.Println("ERROR")
					fmt.Println(err)
				}
			}
		} else {
			fmt.Println(err)
		}

	} else {
		fmt.Println(err)
	}

}
`
It works for the first frame only (I call frame 0)
but not on the others. This is an excerpts of the output:

`
FRAME 1 packageFrame
BY
name
map[using:name value:packageFrame]ERROR
Unable to locate element: packageFrame
FRAME 2 classFrame
BY
name
map[using:name value:classFrame]ERROR
Unable to locate element: classFrame
`
Why it doesn't work. There is a mistake on my part? It's an error on marionette_client or on Firefox.
I trie Firefov 52,2esr and 54. Do you have the same problem?

**Comment by njasm** [comment]
@rankinmark ,
Marionette implementation is heavily based on the webdriver specification. With this in mind let me give you an example that might show that your HTMLSource function might have a bug.

In webdriver, when you switch to a frame or element, your're giving context, and moving to a node, if you call other functions on the client like FindElement, you are on that node's context, see it as the root node.

Now imagine the following example html:

```html
<html>
  <body>
    <!-- stuff -->
    <frame name="frameOne">
      <!-- more stuff -->
      <frame name= "frameTwo">
        <!-- yet more stuff -->
      </frame>
    </frame>
    <frame name="frameThree">
      <!-- ... -->
    </frame>
  </body>
</html>
```

if I, Navigate to this page, and do a ``frames, err := client.FindElements(marionette_client.By(marionette_client.TAG_NAME), "frame")`` like you do, we'll get a collection of three elments.

if we ``SwitchToFrame()`` in a ``for`` loop, we might get into "frameTwo", but last iteration will error cos "frameThree" is not in the scope of your current frame/node, you're currently inside "frameTwo".

Take in consideration, and I don't really remember this part of the spec, by i believe you cannot jump between frame nodes, you have to "Navigate them".

try to change your code in 
```go
	for i, framename := range framenames {
		fmt.Printf("FRAME %d %s\r\n", i, framename)

		err = client.SwitchToFrame(marionette_client.By(marionette_client.NAME), framename)
		//err = client.SwitchToFrame(marionette_client.By(marionette_client.ID), frame.Id())
		if err == nil {
			fmt.Println("NOERROR")
			fmt.Println(gethtml(client))
		} else {
			fmt.Println("ERROR")
			fmt.Println(err)
		}
	}
``` 

and tell me if it worked, I hope it helps.

**Comment by njasm** [comment]
btw.. Firefox version 53.0.3 is the one that development and support is given.. so use that version

**Comment by rankinmark** [comment]
Thanks, your explanation helped me to find the solution: I added client.SwitchToParentFrame() at the end of the loop and now it works flawlessly.
I currently have win xp so I can't install Firefox 53 right now. 
Now I don't like using the name attribute as a reference to frames because they are not mandatory in html e I think now they are deprecated, But using frame.Id() it doesn't work, even for the first frame.
`
for _, frame := range frames {
				//framenames = append(framenames, frame.Attribute("name"))
				framenames = append(framenames, frame.Id())
			}

			for i, framename := range framenames {

				fmt.Printf("FRAME %d %s\r\n", i, framename)

				//err = client.SwitchToFrame(marionette_client.By(marionette_client.NAME), framename)
				err = client.SwitchToFrame(marionette_client.By(marionette_client.ID), framename)
				if err == nil {
					fmt.Println("NOERROR")
					fmt.Println(gethtml(client))
				} else {
					fmt.Println("ERROR")
					fmt.Println(err)
				}
				err := client.SwitchToParentFrame()
				if err == nil {
					fmt.Println(err)
				}
			}
`
So 
framenames = append(framenames, frame.Id())
and 
err = client.SwitchToFrame(marionette_client.By(marionette_client.ID), framename)
are not correct?

I get this error message 1 per frame:
Unable to locate element: 2a3f26ba-1d68-43a0-b6af-2d0fc232a39c
Unable to locate element: c1eb7773-f7be-4c14-aa54-1095bc8a505f
Unable to locate element: 8d765c89-3ad0-4c53-89eb-88ebf7636733

or firefox 52 doesn't support it?

**Comment by rankinmark** [comment]
Could it be that the FindElement method in SwitchtoFrame does not work if a uuid is used ?

`func (c *Client) SwitchToFrame(by By, value string) error {

	//with current marionette implementation we have to find the element first and send the switchToFrame
	//command with the UUID, else it wont work.
	//https://bugzilla.mozilla.org/show_bug.cgi?id=1143908
	frame, err := c.FindElement(by, value)
	if err != nil {
		return err
	}

	_, err = c.transport.Send("switchToFrame", map[string]interface{}{"element": frame.Id(), "focus": true})
	if err != nil {
		return err
	}

	return nil
}
`

**Comment by rankinmark** [comment]
Solved! I created a new method without FindElement and work flawlessly.

**Comment by njasm** [comment]
@rankinmark nice to know that.
but let me tell you that your are miss interpreting the ``element.Id()``, the method `Ìd()``return the internal webdriver ID, that's a uuid, and what you probably talkin about it's the HTML Id Attribute.

**Comment by rankinmark** [comment]
I need the internal uuid not the element id, because it's unique and it has always a non-empty value.
client.SwitchToFrame(marionette_client.By(marionette_client.ID), id) method search by html id? If so there isn' t a bug, otherwise there is. Nonetheless I create a method in client.go to switch to a frame by uuid and that is what I need. My aim is to access every frame/iframe of potentially every webpage on the net.  So I need to enumerate them and execute my javascript code on them even if they don't have an html name or an html id.
