### ISSUE TITLE
Opening more than one tab and get a pointer to everyone of them

### ISSUE THREAD

**Issue by rankinmark** [njasm/marionette_client#19]
I wanted to open more than one tab on firefox via marionette_client, but I need a reference, a pointer to them. My aim is to open for example 10 tabs in parallel with 10 different urls and after they are loaded get for example their html source. Is it possible with marionette_client?

**Comment by njasm** [comment]
@rankinmark yes, you can. you can do everything that webdriver spec allows you to.

You'll have to track and manage the number of windows you're opening and what URL is on each one. You'll need to work with ``CurrentWindowHandle(), SwitchToWindow()`` and ``WindowHandles()`` client methods. 
To open new tabs you'll probably will need to do it throw the execution of javascript or some other method.

Google for webdriver open another tab. you'll find a lot of references and strategies about it.

**Comment by rankinmark** [comment]
Thank you it works.
