### ISSUE TITLE
Take Screenshot issue

### ISSUE THREAD

**Issue by njasm** [njasm/marionette_client#2]
wrongly decoding response..

**Comment by njasm** [comment]
@georgethomas111 it's fixed 👍 #1

**Comment by georgethomas111** [comment]
Thanks a lot. I will send patches or file issues if I find something. 👍 Planning to run this on the server. It should be interesting.

**Comment by njasm** [comment]
ok cool. don't forget to tell your Firefox production installation to not auto-update, nor check for updates.
Since the marionette team are still making changes to the protocol, a new version of Firefox might break the implementation... I suggest for now to you manually update new versions of Firefox in production after testing the client with the new versions in a controlled environment.

If you have any issues. keep me posted! have fun.

**Comment by njasm** [comment]
@georgethomas111 I've been actively adding new features and doing some refactoring.. if you already using an outdated (compared with the master branch) version live, take in considerations that things will break if you update directly in production.

btw.. the method Screenshot() will return (string, error) instead of (*response, error)
the string is the image in base64.

**Comment by georgethomas111** [comment]
@njasm Thanks for the heads up. Nice to see the project becoming better. We use a vendoring tool which should take care of it. I will keep my project updated with the changes.

**Comment by njasm** [comment]
:+1:
