### ISSUE TITLE
client always disconnects after 5 minutes

### ISSUE THREAD

**Issue by pnie** [njasm/marionette_client#21]
A deadline is set on connection, and it is never refreshed:
https://github.com/njasm/marionette_client/blob/4a4a5dbec1660416f99aa416c5caf5feda9ac629/transport.go#L60

After 5 minutes, every request to a server returns i/o timeout error.

**Comment by njasm** [comment]
@pnie can you test this branch out?

I did some tests and the issues seams to be fixed now, can you help confirm that with your use cases?

**Comment by pnie** [comment]
It works without disconnecting now. Thanks.

**Comment by njasm** [comment]
@pnie merged, thanks!
